version: 2.1
jobs:
  build:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: npm test
workflows:
    version: 2.1
    build-deploy:
      jobs:
        - build
        - test:
            requires:
              - build
