version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build-and-test:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: npm install
      - run: npm test
  compose:
    docker:
      - image: cibuilds/docker:19.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker build -t mfunaki/docker-web-app
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        
              # an else block will be added in the future for a staging release
              if git log -1 --pretty=%s | grep "\[Release\]"; then
                echo "Publishing mfunaki/node to Docker Hub production."
                docker push mfunaki/docker-web-app
              else
                echo "Skipping publishing."
              fi
            fi          

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - build-and-test
      - compose:
          requires:
            - build-and-test
